src/Entity/Project.php
<?php

namespace App\Entity;

use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"name"})
     *
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProjectReference", mappedBy="project", orphanRemoval=true)
     * @ORM\OrderBy({"position"="ASC"})
     */
    private $projectReferences;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProjectImage", mappedBy="project", orphanRemoval=true)
     */
    private $projectImages;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="likedProjects")
     */
    private $likeUsers;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="project", cascade={"remove"}, orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->projectReferences = new ArrayCollection();
        $this->projectImages = new ArrayCollection();
        $this->likeUsers = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function isPublished(): bool
    {
        return $this->publishedAt !== null;
    }

    /**
     * @return Collection|ProjectReference[]
     */
    public function getProjectReferences(): Collection
    {
        return $this->projectReferences;
    }

    /*public function addProjectReference(ProjectReference $projectReference): self
    {
        if (!$this->projectReferences->contains($projectReference)) {
            $this->projectReferences[] = $projectReference;
            $projectReference->setProject($this);
        }

        return $this;
    }

    public function removeProjectReference(ProjectReference $projectReference): self
    {
        if ($this->projectReferences->contains($projectReference)) {
            $this->projectReferences->removeElement($projectReference);
            // set the owning side to null (unless already changed)
            if ($projectReference->getProject() === $this) {
                $projectReference->setProject(null);
            }
        }

        return $this;
    }*/

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|ProjectImage[]
     */
    public function getProjectImages(): Collection
    {
        return $this->projectImages;
    }

    /*public function addProjectImage(ProjectImage $projectImage): self
    {
        if (!$this->projectImages->contains($projectImage)) {
            $this->projectImages[] = $projectImage;
            $projectImage->setProject($this);
        }

        return $this;
    }

    public function removeProjectImage(ProjectImage $projectImage): self
    {
        if ($this->projectImages->contains($projectImage)) {
            $this->projectImages->removeElement($projectImage);
            // set the owning side to null (unless already changed)
            if ($projectImage->getProject() === $this) {
                $projectImage->setProject(null);
            }
        }

        return $this;
    }*/

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getLikeUsers(): Collection
    {
        return $this->likeUsers;
    }

    public function addLikeUser(User $likeUser): self
    {
        if (!$this->likeUsers->contains($likeUser)) {
            $this->likeUsers[] = $likeUser;
        }
        $this->setLikes();

        return $this;
    }

    public function removeLikeUser(User $likeUser): self
    {
        if ($this->likeUsers->contains($likeUser)) {
            $this->likeUsers->removeElement($likeUser);
        }
        $this->setLikes();

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->likes;
    }

    public function setLikes(): self
    {
        $this->likes = $this->likeUsers->count();

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProject($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getProject() === $this) {
                $comment->setProject(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @Groups("main")
     */
    protected $email;
    /**
     * @Groups("main")
     */
    protected $username;
    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     */
    private $firstName;
    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     */
    private $lastName;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ApiToken", mappedBy="user", orphanRemoval=true)
     */
    private $apiTokens;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Project", mappedBy="author")
     */
    private $projects;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Project", mappedBy="likeUsers")
     */
    private $likedProjects;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author")
     */
    private $comments;

    public function __construct()
    {
        parent::__construct();
        $this->apiTokens = new ArrayCollection();
        $this->projects = new ArrayCollection();
        $this->projectReferences = new ArrayCollection();
        $this->likedProjects = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Overridden so that username is now optional
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->setUsername($email);
        return parent::setEmail($email);
    }

    /**
     * @return Collection|ApiToken[]
     */
    public function getApiTokens(): Collection
    {
        return $this->apiTokens;
    }

    public function addApiToken(ApiToken $apiToken): self
    {
        if (!$this->apiTokens->contains($apiToken)) {
            $this->apiTokens[] = $apiToken;
            $apiToken->setUser($this);
        }

        return $this;
    }

    public function removeApiToken(ApiToken $apiToken): self
    {
        if ($this->apiTokens->contains($apiToken)) {
            $this->apiTokens->removeElement($apiToken);
            // set the owning side to null (unless already changed)
            if ($apiToken->getUser() === $this) {
                $apiToken->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
            $project->setAuthor($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->projects->contains($project)) {
            $this->projects->removeElement($project);
            // set the owning side to null (unless already changed)
            if ($project->getAuthor() === $this) {
                $project->setAuthor(null);
            }
        }

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath()
    {
        return UploaderHelper::PROFILE_IMAGE.'/'.$this->getImageFilename();
    }

    /**
     * @return Collection|Project[]
     */
    public function getLikedProjects(): Collection
    {
        return $this->likedProjects;
    }

    public function addLikedProject(Project $likedProject): self
    {
        if (!$this->likedProjects->contains($likedProject)) {
            $this->likedProjects[] = $likedProject;
            $likedProject->addLikeUser($this);
        }

        return $this;
    }

    public function removeLikedProject(Project $likedProject): self
    {
        if ($this->likedProjects->contains($likedProject)) {
            $this->likedProjects->removeElement($likedProject);
            $likedProject->removeLikeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Project;
use App\Form\ProjectFormType;
use App\Repository\CategoryRepository;
use App\Repository\ProjectRepository;
use App\Service\UploaderHelper;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Validator\ValidatorInterface;


class ProjectController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     */
    public function homepage(ProjectRepository $projectRepository, Request $request, PaginatorInterface $paginator)
    {
        if (!$this->getUser()) {
            return $this->render('project/landing.html.twig', [
                'controller_name' => 'ProjectController',
            ]);
        }

        $filter = $request->query->get('filter');

        if (!is_null($filter) && $filter === 'likes') {
            $queryBuilder = $projectRepository->getAllPublishedLikedByQueryBuilder($this->getUser()->getId());

        } else {
            $queryBuilder = $projectRepository->getAllPublishedByLikesQueryBuilder();
        }

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            11/*limit per page*/
        );

        return $this->render('project/homepage.html.twig', [
            'controller_name' => 'ProjectController',
            'pagination' => $pagination,
            'filter' => $filter,
        ]);
    }

    /**
     * @Route("/launch", name="app_landing")
     */
    public function landing(ProjectRepository $projectRepository, Request $request)
    {
        return $this->render('project/landing.html.twig', [
        ]);
    }

    /**
     * @Route("/project/{slug}", name="project_show")
     * @IsGranted("ROLE_USER")
     */
    public function show(Project $project, Request $request, EntityManagerInterface $entityManager)
    {
        $like = $project->getLikeUsers()->contains($this->getUser());

        $comment = new Comment();

        $form = $this->createFormBuilder($comment)
            ->add('content')
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAuthor($this->getUser());
            $comment->setProject($project);

            if (!$comment->getCreatedAt()) {
                $comment->setCreatedAt(new \DateTime());
            }

            $comment->setUpdatedAt(new \DateTime());

            $entityManager->persist($comment);
            $entityManager->flush();

            $this->addFlash('success','Comment posted !');
            return $this->redirect($request->getUri());
        }

        return $this->render('project/show.html.twig', [
            'controller_name' => 'ProjectController',
            'project' => $project,
            'like' => $like,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/project/{slug}/like", name="project_like", methods={"POST"})
     * @IsGranted("ROLE_USER")
     */
    public function like(Project $project, ProjectRepository $projectRepository, EntityManagerInterface $entityManager)
    {
        if ($project->getLikeUsers()->contains($this->getUser())) {
            $project->removeLikeUser($this->getUser());
        } else {
            $project->addLikeUser($this->getUser());
        }

        $entityManager->persist($project);
        $entityManager->flush();

        return new JsonResponse(['hearts' => $project->getLikeUsers()->count()]);
    }

    /**
     * @Route("/explore", name="project_filter")
     * @IsGranted("ROLE_USER")
     */
    public function filter(ProjectRepository $projectRepository, CategoryRepository $categoryRepository, Request $request, PaginatorInterface $paginator)
    {
        $categories = $categoryRepository->findAll();
        $filter = $request->query->get('filter');

        if ($filter) {
            $queryBuilder = $projectRepository->getAllPublishedByCategoryQueryBuilder($filter);
        } else {
            $queryBuilder = $projectRepository->getAllPublishedOrderedByNewestQueryBuilder();
        }

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            20/*limit per page*/
        );

        return $this->render('project/explore.html.twig', [
            'controller_name' => 'ProjectController',
            'pagination' => $pagination,
            'categories' => $categories,
            'filter' => $filter
        ]);
    }
}

templates/project/explore.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Horizon{% endblock %}

{% block OpenGraph %}
    <meta property="og:title" content="Horizon" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.horizon-technology.fr/explore" />
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/main-pages.css') }}">
{% endblock %}


{% block content_body %}
    <div class="row">
        <div class="dropdown show col-sm-3">
            <a class="btn btn-secondary dropdown-toggle filter-select" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Category
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item {{ filter ? '' : 'selected' }}" href="{{ path('project_filter') }}">Recent</a>
                {% for category in categories %}
                    <a href="{{ path('project_filter', {'filter': {'name': category.name, 'id': category.id}}) }}" class="dropdown-item
                            {% if filter %}
                                {{ (category.name in filter.name) ? 'selected' : '' }}
                            {% endif %}">
                        {{ category.name }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <h1 class="col-sm-9">{{ filter ? filter.name : 'Recent' }} ({{ pagination.getTotalItemCount }})</h1>
    </div>
    <div class="row justify-content-center">
        {% if pagination %}
            <div class="col-sm-12 other-projects mb-5 mt-5">
                {% for project in pagination %}
                    {% set firstImage = project.projectImages|first %}
                    <div>
                        <a href="{{ path('project_show', {slug: project.slug}) }}">
                            <img src="{{ firstImage.imagePath|imagine_filter('squared_thumbnail_small') }}" alt="project picture">
                            <p>{{ project.name|title|truncate(20, true) }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
            {{ knp_pagination_render(pagination) }}
        {% else %}
            <div class="d-flex justify-content-center m-5">
                <p class="m-5">Looks like you haven't liked any projects yet !</p>
            </div>
        {% endif %}
    </div>

{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/filter.js') }}"></script>
{% endblock %}

templates/project/homepage.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Horizon{% endblock %}

{% block OpenGraph %}
    <meta property="og:title" content="Horizon" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.horizon-technology.fr/" />
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/main-pages.css') }}">
{% endblock %}

{% block content_body %}

<div class="row justify-content-center">
    <a class="project-filter-link {{ filter ? '' : 'selected' }}" href="{{ path('app_homepage') }}">Popular</a>
    <a class="project-filter-link {{ filter ? 'selected' : '' }}" href="{{ path('app_homepage', {'filter': 'likes'}) }}" >Likes</a>
</div>
<div class="row flex-wrap justify-content-center project-section">
    {% for project in pagination %}
        {% set firstImage = project.projectImages|first %}
            {% if loop.first %}
                <div class="col-sm-12 trend-project">
                    <a href="{{ path('project_show', {slug: project.slug}) }}">
                        <img src="{{ firstImage.imagePath|imagine_filter('trend_thumbnail_medium') }}" alt="project picture">
                    </a>
                    <div class="trend-project-desc">
                        <a class="project-author-info" href="{{ path('profile_show', {'id': project.author.id}) }}">
                            {% if project.author.imageFilename %}
                                <img class="rounded-circle" src="{{ project.author.imagePath|imagine_filter('squared_thumbnail_small') }}" alt="profil picture">
                            {% else %}
                                <i class="far fa-laugh-beam default-profile-image"></i>
                            {% endif %}
                            <p>{{ project.author.firstName }} {{ project.author.lastName }}</p>
                        </a>
                        <a href="{{ path('project_show', {slug: project.slug}) }}">
                            <p>{{ project.name|title }}</p>
                        </a>
                        <span class="project-date">{{ project.publishedAt|date("m.d.Y") }}</span>
                    </div>
                </div>
            {% endif %}
    {% endfor %}
        {% if pagination %}
            <div class="col-sm-12 other-projects mb-5">
                {% for project in pagination %}
                    {% set firstImage = project.projectImages|first %}
                    {% if not loop.first %}
                        <div>
                            <a href="{{ path('project_show', {slug: project.slug}) }}">
                                <img src="{{ firstImage.imagePath|imagine_filter('squared_thumbnail_small') }}" alt="project picture">
                                <p>{{ project.name|title|truncate(20, true) }}</p>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {{ knp_pagination_render(pagination) }}
        {% else %}

            <div class="d-flex justify-content-center m-5">
                <p class="m-5">Looks like you haven't liked any projects yet !</p>
            </div>
        {% endif %}
</div>
{% endblock %}

templates/project/landing.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome to Horizon!{% endblock %}

{% block OpenGraph %}
    <meta property="og:title" content="Welcome to Horizon!" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.horizon-technology.fr" />
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/transition.css') }}">
{% endblock %}

{% block nav %}{% endblock %}

{% block body %}
    <div class="transition"></div>
    <div class="content">
        <h1>Welcome to Horizon</h1>
        <p>Share your ideas to make it happen.</p>
        <div class="link">
            <a class="cta" href="{{ path('fos_user_security_login') }}">Login</a>
            <a class="cta" href="{{ path('fos_user_registration_register') }}">Register</a>
        </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/transition.js') }}"></script>
{% endblock %}

templates/project/show.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Horizon {{ project.author.firstName }}'s project{% endblock %}

{% block OpenGraph %}
    <meta property="og:title" content="Horizon {{ project.author.firstName }}'s project" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="http://www.horizon-technology.fr/project/{{ project.slug }}" />
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/project.css') }}">
{% endblock %}


{% block content_body %}
    <div class="project-heading">
        <a href="{{ path('project_filter', {'filter': {'name': project.category.name, 'id': project.category.id}}) }}">{{ project.category.name }}</a>
        <h1>{{ project.name }}</h1>
        {% if project.author is same as(app.user) %}
            <a href="{{ path('project_edit', {'slug': project.slug}) }}"><i class="fas fa-cog edit-icon"></i></a>
        {% endif %}
    </div>


    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            {% for image in project.projectImages %}
                {% if project.projectImages|length > 1  %}
                    {% if loop.first %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index }}" class="active"></li>
                    {% else %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index }}"></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ol>
        <div class="carousel-inner">
            {% for image in project.projectImages %}
                {% if loop.first %}
                    <div class="carousel-item active">
                        <a class="d-flex justify-content-center" href="{{ uploaded_asset(image.imagePath) }}" target="_blank">
                            <img class="d-block" src="{{ image.imagePath|imagine_filter('slideshow') }}" alt="First slide">
                        </a>
                    </div>
                {% else %}
                    <div class="carousel-item">
                        <a class="d-flex justify-content-center" href="{{ uploaded_asset(image.imagePath) }}" target="_blank">
                            <img class="d-block" src="{{ image.imagePath|imagine_filter('slideshow') }}" alt="Other slide">
                        </a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        {% if project.projectImages|length > 1  %}
            <a class="carousel-control-prev carousel-control" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon carousel-control-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next carousel-control" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon carousel-control-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        {% endif %}
    </div>
    <div class="meta-project">
        <div class="heart">
            <span class="js-like-project-count">{{ project.likeUsers|length }}</span>
            <a href="{{ path('project_like', {'slug': project.slug}) }}" class="{% if like %}fas{% else %}far{% endif %} fa-heart like-article js-like-project"></a>
        </div>
        <a class="project-author-info" href="{{ path('profile_show', {'id': project.author.id}) }}">
            {% if project.author.imageFilename %}
                <img class="rounded-circle" src="{{ project.author.imagePath|imagine_filter('squared_thumbnail_small') }}" alt="profil picture">
            {% else %}
                <i class="far fa-laugh-beam default-profile-image"></i>
            {% endif %}
            <p>{{ project.author.firstName }} {{ project.author.lastName }}</p>
        </a>
    </div>
    <div class="row">
        <div class="{{ project.projectReferences|length ? 'col-sm-9' : 'col-sm-12' }}">
            <div class="project-text mt-3">
                <p>{{ project.description }}</p>
            </div>
            <span class="project-date">{{ project.publishedAt|date("m.d.Y") }}</span>
        </div>
    {% if project.projectReferences|length  %}
        <div class="d-flex-column col-sm-3">
            <ul class="list-group pt-3">
                {% for reference in project.projectReferences %}
                    <li class="list-group-item d-flex reference-item">
                        <p>{{ reference.originalFilename }}</p>
                        <span>
                        <a href="/project/references/{{ reference.id }}/download"><span class="fa fa-download"></span></a>
                    </span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    </div>
    {% if project.published %}
        <div class="mt-5">
            {{ form_start(form) }}
            {{ form_row(form.content, {'label': 'Comment'}) }}

            <button type="submit" class="button-classic">Valider</button>
            {{ form_end(form) }}
        </div>
    {% endif %}
    {% if project.comments|length %}
    <div class="row mt-5">
        {% for comment in project.comments %}
        <div class="d-flex d-flex-column col-sm-12 comment p-2 mt-3">
            <div class="d-flex">
                <a class="project-author-info" href="{{ path('profile_show', {'id': comment.author.id}) }}">
                    {% if comment.author.imageFilename %}
                        <img class="rounded-circle" src="{{ comment.author.imagePath|imagine_filter('squared_thumbnail_small') }}" alt="profil picture">
                    {% else %}
                        <i class="far fa-laugh-beam default-profile-image"></i>
                    {% endif %}
                    <p>{{ comment.author.firstName }} {{ comment.author.lastName }}</p>
                </a>
                {% if comment.author is same as(app.user) or project.author is same as(app.user) %}
                    <a class="comment-delete" href="{{ path('comment_delete', {'id': comment.id}) }}"><i class="fas fa-times"></i></a>
                {% endif %}
            </div>
            <p class="comment-content">{{ comment.content }}</p>
            <span class="project-date">{{ comment.createdAt|date("m.d.Y") }}</span>
        </div>
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/project.js') }}"></script>
{% endblock %}